# Generated by Django 3.2 on 2021-09-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ref',
            field=models.URLField(null=True),
        ),
    ]
