# Generated by Django 3.2 on 2021-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_book_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ref',
            field=models.URLField(max_length=555, null=True),
        ),
    ]
