# Generated by Django 3.2 on 2021-09-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210907_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Price_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField()),
                ('special_price', models.IntegerField()),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
            options={
                'db_table': 'Book_Price_history',
            },
        ),
    ]
