# Generated by Django 3.2 on 2021-09-13 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_price_history',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
