# Generated by Django 3.2 on 2021-09-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_book_price_history_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_price_history',
            old_name='related_to',
            new_name='Book_id',
        ),
    ]
